prd:
  catalog_name: mlops_prod
  schema_name: acikgozm
  pipeline_id: 1818db79-f551-49bb-ad4f-f61cac9d91fc
acc:
  catalog_name: mlops_acc
  schema_name: acikgozm
  pipeline_id: 94748db79-f551-49bb-ad4f-f61cac9d91fc
dev:
  catalog_name: mlops_dev
  schema_name: acikgozm
  pipeline_id: 01b28c81-5ea4-4e27-99c5-6fdfdc275566

#default values for notebook implementations
# catalog_name: mlops_dev
# schema_name: acikgozm


experiment_name: /Shared/hotel-reservations

model:
  name: hotel_reservations_model
  artifact_path: lightgbm-pipeline-model

parameters:
  learning_rate: 0.02
  n_estimators: 500
  num_leaves: 17

num_features:
  - name: no_of_adults
    dtype: int16
    alias: no_of_adults
  - name: no_of_children
    dtype: int16
    alias: no_of_children
  - name: no_of_weekend_nights
    dtype: int16
    alias: no_of_weekend_nights
  - name: no_of_week_nights
    dtype: int16
    alias: no_of_week_nights
  - name: required_car_parking_space
    dtype: int16
    alias: required_car_parking_space
  - name: lead_time
    dtype: int16
    alias: lead_time
  - name: arrival_year
    dtype: int16
    alias: arrival_year
  - name: arrival_month
    dtype: int16
    alias: arrival_month
  - name: arrival_date
    dtype: int16
    alias: arrival_date
  - name: repeated_guest
    dtype: int16
    alias: repeated_guest
  - name: no_of_previous_cancellations
    dtype: int16
    alias: no_of_previous_cancellations
  - name: no_of_previous_bookings_not_canceled
    dtype: int16
    alias: no_of_previous_bookings_not_canceled
  - name: avg_price_per_room
    dtype: float64
    alias: avg_price_per_room
  - name: no_of_special_requests
    dtype: int16
    alias: no_of_special_requests

cat_features:
  - name: Booking_ID
    dtype: object
    alias: booking_id
  - name: type_of_meal_plan
    dtype: object
    alias: type_of_meal_plan
  - name: room_type_reserved
    dtype: object
    alias: room_type_reserved
  - name: market_segment_type
    dtype: object
    alias: market_segment_type

target:
  name: booking_status
  dtype: category
  alias: booking_status

features:
  numerical:
  - no_of_adults
  - no_of_children
  - no_of_weekend_nights
  - no_of_week_nights
  - required_car_parking_space
  - lead_time
  # - arrival_year
  # - arrival_month
  # - arrival_date
  - repeated_guest
  - no_of_previous_cancellations
  - no_of_previous_bookings_not_canceled
  - avg_price_per_room
  - no_of_special_requests
  # - arrival

  categorical:
  - type_of_meal_plan
  - room_type_reserved
