name: CI

on:
  push:
    branches:
      - main
      - hotel_reservation_data_ingestion
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Set up Python
        run: | # uv python install 3.11
          uv venv -p 3.11 venv
          # source venv/bin/activate
          echo "source venv/bin/activate" >> $GITHUB_ENV
          which python

      - name: Verify src directory exists
        run: |
          if [ ! -d "src" ]; then
            echo "src directory is missing. Creating src directory."
            mkdir src
          fi

      - name: Install the dependencies
        run: |
          # uv sync --all-extras
          # source venv/bin/activate
          uv pip install -r pyproject.toml --all-extras --link-mode=copy  --no-cache-dir
          uv lock
          uv pip install -e . --link-mode=copy  --no-cache-dir
          pre-commit run --all-files
          pytest


      - name: Run pre-commit checks
        run: |
          # uv run pre-commit run --all-files
          pre-commit run --all-files

      - name: Install and run tests
        run: |
          # uv --version
          # pip install --upgrade uv
          # uv build
          # cp ./dist/*.whl ./dist/hotel_reservations-latest-py3-none-any.whl --overwrite
          # uv pip install ./dist/*.whl
          # uv pip run pytest
          pytest
